DROP DATABASE IF EXISTS bill_s_7;
CREATE DATABASE bill_s_7;

USE bill_s_7;

CREATE TABLE tacos (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200),
	devoured BOOLEAN NOT NULL DEFAULT false
);